name: CI setup for Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: 
  my-job: 
    name: My Job
    runs-on: ubuntu-16.04
    steps: 
    - name: Print a greeting
      run: |
        ls
        echo Hello there!
        
        
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with: 
        go-version: 1.13.7
        
    - name: Check Go Version
      run: | 
        go version
        ls
        
        
    - name: Checkout my codes
      uses: actions/checkout@v2

    - name: Check file system
      run: ls
      #cat calc.go
      
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        path: remoteRepo
        token: ${{ secrets.GO_REMOTE }}
        
    - name: Check files
      run:  | 
        ls
        cd remoteRep
        ls
        cat myText.txt
        cd ..
        
    - name: Install dependencies
      run: | 
        go get github.com/franela/goblin
        go get github.com/tebeka/go2xunit
        go test -v
        go test -v | go2xunit > report.xml
        
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: report.xml

    - if: ${{ failure() }}
    #using name instead of - name to ensure that name is tagged ONLY if there is a failure
      name: Create Issues 
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: Build Failed
        token: ${{secrets.GITHUB_TOKEN}}
        assignees: ${{github.actor}}
        labels: workflow-failed
        body: Workflow failed for commit ${{github.sha}}
