name: CI setup for Go

on:
  push:
    branches: [main]
    
jobs: 
  my-job: 
    name: My Job
    runs-on: ubuntu-16.04
    steps: 
    - name: Print a greeting
      run: |
        echo Hello there!
        ls
        
    - name: Setup Go environment
      uses: actions/setup-go@v2.1.3
      with:
        # The Go version to download (if necessary) and use. Supports semver spec and ranges.
        go-version: 1.15.8
        
    - name: Check Go Version
      run: | 
        go version
        ls
        
    - name: Checkout my codes
      uses: actions/checkout@v2

    - name: Check file system
      run: ls
      
    - name: Checkout private repo
      uses: actions/checkout@v2
      with:
        repository: lowkh2/GoSchoolRemoteExample
        path: remoteRep
        token: ${{ secrets.SECRET }}
      
    - name: Check files
      run:  | 
        ls
        cd remoteRep
        ls
        cat myText.txt
        cd ..
